export default {
    CHATTER_ENTRY_MOVED :  "CHATTER_ENTRY_MOVED",
    CHATTER_OPEN_EDITOR :  "CHATTER_OPEN_EDITOR",
    CHATTER_ENTRY_CHANGED : "CHATTER_ENTRY_CHANGED",
    CHATTER_ADD : "CHATTER_ADD",
    CHATTER_PLAY : "CHATTER_PLAY",
    CHATTER_EXPORT : "CHATTER_EXPORT",
    CHATTER_UPLOAD : "CHATTER_UPLOAD",
    CHATTER_SETTINGS : "CHATTER_SETTINGS",
    CHATTER_DELETE_SELECTED : "CHATTER_DELETE_SELECTED",
    CHATTER_SELECTION_CHANGED: "CHATTER_SELECTION_CHANGED",
    CHATTER_IMPORT_HTML_STRING : "CHATTER_IMPORT_HTML_STRING",

}